### ISSUE TITLE
No Redirection and Table Updating after Payment Issues

### ISSUE THREAD

**Issue by Kivaru** [bryceandy/laravel-selcom#1]
I have been starting using your excellent package, thank you for that but I have faced no redirection issue when I set it to false, it gives me undefined offset 0 and another thing I have faced is selcom_payments table is not updated even if transaction is successful. Can I get help from this and thank you in advance

**Comment by bryceandy** [comment]
Which type of checkout are you attempting? Also show what you have done

**Comment by Kivaru** [comment]
okay, so what I have done is follow your documentation which was pretty straightforward:
this is for the Checkout payments using USSD

    public function checkoutPayment(Request $request)
    {
        return Selcom::checkout([
            'name' => $request->name.' '.$request->name, 
            'email' => $request->email,
            'phone' => $request->phone,
            'amount' => $request->selcomPrice,
            'transaction_id' =>Str::random(10),
            'no_redirection' => true,
        ]);
    }

which works perfect when `no_redirection` is `true` but if `false` I get undefined offset:0 at HandlesCheckout.php:121.
Second thing is I don't get `selcom_payments` updated even after payment has been successfully done. I have followed the documentation for creating listener for Checkout webhook/callback event and my listener looks like this (which is typically what you have done)

    public function handle(CheckoutWebhookReceived $event)
    {
        // Get the order id
        $orderId = $event->orderId;
        //
        // Fetch updated record in the database, and do what you need with it
        $status = DB::table('selcom_payments')
            ->where('order_id', $orderId)
            ->value('payment_status');

        dd($status);
        
        if ($status === 'PENDING') {
            Selcom::orderStatus($orderId); // Or dispatch a job minutes later to query order status
        }
    }

but I still can't get table `selcom_payments` updated, I don't know what I miss or skipped but I tried to follow your documentation thoroughly

**Comment by bryceandy** [comment]
> but if false I get undefined offset:0

With USSD it is always `true` as stated in the documentation.

> I still can't get table selcom_payments updated

What do you get when you dump `dd($status);`?

**Comment by Kivaru** [comment]
okay, nothing man, dd is not hit I guess

**Comment by bryceandy** [comment]
That means Selcom is not sending the request to your webhook. This is normal especially in the test environment, if it happens on the live environment just contact their developer support - tell them your webhook route `/checkout-callback` is not hit.

Or you can make a custom  implementation to query the status:

    // Do the payment first...
    Selcom::checkout($data);

    // Fetch the orderId of the current checkout payment
    $orderId = DB::table('selcom_payments')
        ->where('transid', $data['transaction_id'])
        ->value('order_id');

    // Query the status from Selcom after a certain time. Use a Laravel Job or Scheduler
    // For example, I would create a Job (UpdateSelcomPayment) and dispatch it after 20 seconds

    UpdateSelcomPayment::dispatch($orderId)
        ->delay(now()->addSeconds(20));

If you are familiar with jobs and queue workers and would want to use a job here is how it could look like:

    // App/Jobs/UpdateSelcomPayment.php
    class UpdateSelcomPayment extends ShouldQueue
    {
        public $tries = 0;
        public $orderId;

        public function __construct($orderId)
        {
            $this->orderId = $orderId;
        }

        public function retryUntil()
        {
            // We may set that the job should expire after 30 mins
            return now()->addMinutes(30);
        }

        public function handle() 
        {
           // Query order status from Selcom
           $order = Selcom::orderStatus($this->orderId);

            if ($order['payment_status'] === 'PENDING') {
                // Send the job back to the queue again after maybe 1 minute, so that this job will be retried
                $this->release(now()->addMinute());
            }
            else {
                // Update the table
                DB::table('selcom_payments')
                    ->where('order_id', $this->orderId)
                    ->update([
                        'payment_status' => $order['payment_status'],
                        'updated_at' => now(),
                        'reference' => $order['reference'] ?? null,
                        'selcom_transaction_id' => $order['transid'] ?? null,
                        'channel' => $order['channel'] ?? null,
                        'msisdn' => $order['msisdn'] ?? null,
                    ]);
            }
        }
    }

**Comment by Kivaru** [comment]
Thanks and Appreciates
