### ISSUE TITLE
How to handle multiple products ordering

### ISSUE THREAD

**Issue by Kivaru** [bryceandy/laravel-selcom#2]
Hey, since you are the creator of this amazing package, I would like to hear from you how can I add functionality of ordering bulk products containing different product ids? Because as what I can see, only one product at a time can be processed. Thanks

**Comment by bryceandy** [comment]
Can you give an example of what you want to achieve?
Keep in mind, the package does not have a concept of `products`, only a unique `order_id` which is required by the selcom API. 
It is flexible to customize on your project and associate your own orders or products to the `transid` or `order_id` of the `selcom_payments` table
